version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: vtrendz-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: vtrendz-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
