version: '3.8'

services:
  backend:
    container_name: trendz-backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    container_name: trendz-frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - backend
